apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cache-deployer-role.yaml
  - cache-deployer-rolebinding.yaml
  - cache-deployer-deployment.yaml
images:
  - name: docker.io/mrdojojo/kfp-cache-deployer
    newTag: 2.14.3
labels:
  - includeSelectors: true
    pairs:
      app: cache-deployer
