apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: docker.io/mrdojojo/kfp-inverse-proxy-agent
    newTag: 2.14.3
resources:
  - proxy-configmap.yaml
  - proxy-deployment.yaml
  - proxy-role.yaml
  - proxy-rolebinding.yaml
  - proxy-sa.yaml
