apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metadata-writer-deployment.yaml
  - metadata-writer-role.yaml
  - metadata-writer-rolebinding.yaml
  - metadata-writer-sa.yaml
images:
  - name: docker.io/mrdojojo/kfp-metadata-writer
    newTag: 2.14.3
